basePath: /
definitions:
  routes.Agent:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  routes.Auth:
    properties:
      email:
        type: string
      password:
        type: string
      provider:
        type: string
    type: object
  routes.AutoCaption:
    properties:
      url:
        type: string
    type: object
  routes.AutoClip:
    properties:
      url:
        type: string
    type: object
  routes.Pricing:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  routes.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  routes.UserAgent:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: dev@astrovia.id
    name: API Support
  description: API Gateway Astrovia AI.
  title: Astrovia Gateway API
  version: "1.1"
paths:
  /v1/agents:
    get:
      description: Get list of agent
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.Agent'
            type: array
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get all agent
      tags:
      - Agents
    post:
      consumes:
      - application/json
      description: Create new agent
      parameters:
      - description: Agent info
        in: body
        name: agent
        required: true
        schema:
          $ref: '#/definitions/routes.Agent'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.Agent'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Create agent
      tags:
      - Agents
  /v1/agents/{id}:
    delete:
      description: Delete agent by ID
      parameters:
      - description: Agent ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Delete agent
      tags:
      - Agents
    get:
      description: Get single agent
      parameters:
      - description: Agent ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.Agent'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get agent by ID
      tags:
      - Agents
    put:
      consumes:
      - application/json
      description: Update agent by ID
      parameters:
      - description: Agent ID
        in: path
        name: id
        required: true
        type: string
      - description: Agent info
        in: body
        name: agent
        required: true
        schema:
          $ref: '#/definitions/routes.Agent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.Agent'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Update agent
      tags:
      - Agents
  /v1/agents/public:
    get:
      description: Get list of agent
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.Agent'
            type: array
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get all agent
      tags:
      - Agents
  /v1/astro-zenith/auto-caption:
    get:
      description: Get list of autocaption
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.AutoCaption'
            type: array
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get all autocaption
      tags:
      - AutoCaption
    post:
      consumes:
      - application/json
      description: Create new autocaption
      parameters:
      - description: AutoCaption info
        in: body
        name: autocaption
        required: true
        schema:
          $ref: '#/definitions/routes.AutoCaption'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.AutoCaption'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Create autocaption
      tags:
      - AutoCaption
  /v1/astro-zenith/auto-caption/{id}:
    delete:
      description: Delete autocaption by ID
      parameters:
      - description: AutoCaption ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Delete autocaption
      tags:
      - AutoCaption
    get:
      description: Get single autocaption
      parameters:
      - description: AutoCaption ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.AutoCaption'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get autocaption by ID
      tags:
      - AutoCaption
    put:
      consumes:
      - application/json
      description: Update autocaption by ID
      parameters:
      - description: AutoCaption ID
        in: path
        name: id
        required: true
        type: string
      - description: AutoCaption info
        in: body
        name: autocaption
        required: true
        schema:
          $ref: '#/definitions/routes.AutoCaption'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.AutoCaption'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Update autocaption
      tags:
      - AutoCaption
  /v1/astro-zenith/auto-clip:
    get:
      description: Get list of autoclip
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.AutoClip'
            type: array
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get all autoclip
      tags:
      - AutoClips
    post:
      consumes:
      - application/json
      description: Create new autoclip
      parameters:
      - description: AutoClip info
        in: body
        name: autoclip
        required: true
        schema:
          $ref: '#/definitions/routes.AutoClip'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.AutoClip'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Create autoclip
      tags:
      - AutoClips
  /v1/astro-zenith/auto-clip/{id}:
    delete:
      description: Delete autoclip by ID
      parameters:
      - description: AutoClip ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Delete autoclip
      tags:
      - AutoClips
    get:
      description: Get single autoclip
      parameters:
      - description: AutoClip ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.AutoClip'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get autoclip by ID
      tags:
      - AutoClips
    put:
      consumes:
      - application/json
      description: Update autoclip by ID
      parameters:
      - description: AutoClip ID
        in: path
        name: id
        required: true
        type: string
      - description: AutoClip info
        in: body
        name: autoclip
        required: true
        schema:
          $ref: '#/definitions/routes.AutoClip'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.AutoClip'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Update autoclip
      tags:
      - AutoClips
  /v1/generate-token:
    post:
      consumes:
      - application/json
      description: Generate token
      parameters:
      - description: Auth info
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/routes.Auth'
      produces:
      - application/json
      responses: {}
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Authentication
      tags:
      - Authentication
  /v1/pricing:
    get:
      description: Get list of pricing
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.Pricing'
            type: array
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get all pricing
      tags:
      - Pricing
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: Pricing info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/routes.Pricing'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.Pricing'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Create user
      tags:
      - Pricing
  /v1/pricing/{id}:
    delete:
      description: Delete user by ID
      parameters:
      - description: Pricing ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Delete user
      tags:
      - Pricing
    get:
      description: Get single user
      parameters:
      - description: Pricing ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.Pricing'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get user by ID
      tags:
      - Pricing
    put:
      consumes:
      - application/json
      description: Update user by ID
      parameters:
      - description: Pricing ID
        in: path
        name: id
        required: true
        type: string
      - description: Pricing info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/routes.Pricing'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.Pricing'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Update user
      tags:
      - Pricing
  /v1/user-agents:
    get:
      description: Get list of user agent
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.UserAgent'
            type: array
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get all user agent
      tags:
      - UserAgents
    post:
      consumes:
      - application/json
      description: Create new user agent
      parameters:
      - description: UserAgent info
        in: body
        name: useragent
        required: true
        schema:
          $ref: '#/definitions/routes.UserAgent'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.UserAgent'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Create user agent
      tags:
      - UserAgents
  /v1/user-agents/{id}:
    delete:
      description: Delete user agent by ID
      parameters:
      - description: UserAgent ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Delete user agent
      tags:
      - UserAgents
    get:
      description: Get single user agent
      parameters:
      - description: UserAgent ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.UserAgent'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get user agent by ID
      tags:
      - UserAgents
    put:
      consumes:
      - application/json
      description: Update user agent by ID
      parameters:
      - description: UserAgent ID
        in: path
        name: id
        required: true
        type: string
      - description: UserAgent info
        in: body
        name: useragent
        required: true
        schema:
          $ref: '#/definitions/routes.UserAgent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.UserAgent'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Update user agent
      tags:
      - UserAgents
  /v1/users:
    get:
      description: Get list of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.User'
            type: array
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/routes.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.User'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Create user
      tags:
      - Users
  /v1/users/{id}:
    delete:
      description: Delete user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Delete user
      tags:
      - Users
    get:
      description: Get single user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.User'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get user by ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/routes.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.User'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Update user
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    description: 'Format: Bearer <token>'
    in: header
    name: Authorization
    type: apiKey
  X-Signature:
    description: Signature HMAC SHA256 untuk validasi integritas request
    in: header
    name: X-Signature
    type: apiKey
  X-Timestamp:
    description: 'Timestamp UTC format RFC3339 (contoh: 2025-11-03T09:10:00Z)'
    in: header
    name: X-Timestamp
    type: apiKey
swagger: "2.0"
