basePath: /
definitions:
  routes.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: dev@astrovia.id
    name: API Support
  description: API Gateway Astrovia AI.
  title: Astrovia Gateway API
  version: "1.1"
paths:
  /v1/users:
    get:
      description: Get list of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.User'
            type: array
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/routes.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.User'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Create user
      tags:
      - users
  /v1/users/{id}:
    delete:
      description: Delete user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Delete user
      tags:
      - users
    get:
      description: Get single user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.User'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Get user by ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/routes.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.User'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Update user
      tags:
      - users
securityDefinitions:
  X-Signature:
    description: Signature HMAC SHA256 untuk validasi integritas request
    in: header
    name: X-Signature
    type: apiKey
  X-Timestamp:
    description: 'Timestamp UTC format RFC3339 (contoh: 2025-11-03T09:10:00Z)'
    in: header
    name: X-Timestamp
    type: apiKey
swagger: "2.0"
