basePath: /
definitions:
  routes.Auth:
    properties:
      email:
        type: string
      password:
        type: string
      provider:
        type: string
    type: object
  routes.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  routes.Video:
    properties:
      url:
        type: string
    type: object
info:
  contact:
    email: dev@astrovia.id
    name: API Support
  description: API Gateway Astrovia AI.
  title: Astrovia Gateway API
  version: "1.1"
paths:
  /v1/generate-token:
    post:
      consumes:
      - application/json
      description: Generate token
      parameters:
      - description: Auth info
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/routes.Auth'
      produces:
      - application/json
      responses: {}
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Authentication
      tags:
      - Authentication
  /v1/users:
    get:
      description: Get list of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.User'
            type: array
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/routes.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.User'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Create user
      tags:
      - Users
  /v1/users/{id}:
    delete:
      description: Delete user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Delete user
      tags:
      - Users
    get:
      description: Get single user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.User'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get user by ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/routes.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.User'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Update user
      tags:
      - Users
  /v1/video:
    get:
      description: Get list of video
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.Video'
            type: array
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get all video
      tags:
      - Videos
    post:
      consumes:
      - application/json
      description: Create new video
      parameters:
      - description: Video info
        in: body
        name: video
        required: true
        schema:
          $ref: '#/definitions/routes.Video'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.Video'
      security:
      - X-Signature: []
      - X-Timestamp: []
      summary: Create video
      tags:
      - Videos
  /v1/video/{id}:
    delete:
      description: Delete video by ID
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Delete video
      tags:
      - Videos
    get:
      description: Get single video
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.Video'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Get video by ID
      tags:
      - Videos
    put:
      consumes:
      - application/json
      description: Update video by ID
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: string
      - description: Video info
        in: body
        name: video
        required: true
        schema:
          $ref: '#/definitions/routes.Video'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.Video'
      security:
      - BearerAuth: []
      - X-Signature: []
      - X-Timestamp: []
      summary: Update video
      tags:
      - Videos
securityDefinitions:
  BearerAuth:
    description: 'Format: Bearer <token>'
    in: header
    name: Authorization
    type: apiKey
  X-Signature:
    description: Signature HMAC SHA256 untuk validasi integritas request
    in: header
    name: X-Signature
    type: apiKey
  X-Timestamp:
    description: 'Timestamp UTC format RFC3339 (contoh: 2025-11-03T09:10:00Z)'
    in: header
    name: X-Timestamp
    type: apiKey
swagger: "2.0"
