name: Manual Deploy Go Service

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service to deploy"
        required: true
        type: choice
        options:
          - gateway
          - user
          - global
          - astro-zenith
      tag:
        description: "Docker tag (default: short SHA)"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.${{ github.event.inputs.service }}
          push: true
          tags: |
            fendriknj/astrovia-${{ github.event.inputs.service }}:latest
            fendriknj/astrovia-${{ github.event.inputs.service }}:${{ env.TAG }}
